# 수정 금지!!!!!!!!!
#---------------------------------------------------------
#[finalPJ_TEAM1] 배포 환경 (공인 IP 또는 클라우드 DB)
#---------------------------------------------------------

# 현재 활성화할 프로파일 (개발 시 local, 배포 시 prod)
spring.profiles.active=local

# 포트번호 설정
server.port=8081

# JWT 보안 설정
jwt.secret=v8yB3p6S9zA2dW5f8gH1jK4mN7qT0wXzC2v5b8n1m4q7t0w3x6z9yB2e5h8k1n4p
jwt.expiration=86400000