# 수정 금지!!!!!!!!!

# 배포용 (공인 IP 또는 도메인용) - 배포 테스트 시 도메인 수정 필요
spring.datasource.url=jdbc:postgresql://your-public-ip:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=prod_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA 설정 (운영 모드)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect